### ISSUE TITLE
Media Downloader

### ISSUE THREAD

**Issue by UnwashedMeme** [iDigBio/idigbio-python-client#10]
Request coming out of idigBio Summit VI is for a way to download large segments of media images for local review/processing.

## Desired Workflow 
 * A user would need a working python environment with the idigbio-python-client installed.
 * The user would copy a file from the examples folder and modify that to fit their particular need. E.g.
   * Change the search critera
   * Specify a txt/csv file listing media record uuids they would like downloaded
   * Specify an image size `{webview, fullsize, thumbnail}`; default: `webview`
   * Specify an output directory; default to a subdir of current dir
   * Specify an output filename format, default to: `{mediarecord_uuid}-{size}.jpg`
 * Run the python file to perform the download
  * It should have some basic output of the progress 
  * It should resume gracefully if interrupted

## Work to be done:
 * In the python client core:
    * Implement a downloader that takes a list of mediarecord uuids, size, directory, filename format.
    * Ensure that it can be fed from search results.
 * Write an example file that shows the use with several of the different options in the above workflow
 * Test and document
 * publish

**Comment by danstoner** [comment]
Passing on additional clarification from user:

> Happy Holidays! In working with a couple datasets from iDigBio, I've discovered that it would be helpful to be able to input a list of GUIDs and get out the images associated with them. This would be useful for when I need to code label data (e.g., date) that the data provider did not include in the dwc fields.
> 
> Just a thought from someone working with the data! Thanks, as always, for your work.
> ~Katie
>

**Comment by danstoner** [comment]
Given the amount of user-preference built into the workflow of downloading media, it did not feel right to me to try to put that functionality into the core client itself.

I implemented this requested feature by writing scripts and documentation in examples/fetch_media.

fetch_media.py can do most of the above.

released in v0.8.4.
bf4a3670273425401feee7160c51aafa376e6f69

Closing.
