### ISSUE TITLE
Allow media uploads

### ISSUE THREAD

**Issue by UnwashedMeme** [iDigBio/idigbio-python-client#7]
For work on integration with the [idigbio-media-appliance](https://github.com/iDigBio/idigbio-media-appliance) the python client should be able to upload through to the media api.

We want to handle two cases:
1. Full upload, takes a filereference (the canonical origin of the file) and the media file object itself
2. Verify upload, takes a filereference and the media's etag (md5 hash).

**Comment by godfoder** [comment]
Item two should be more of an "add reference" function. The goal would be to add an additional reference to an existing media object. This is already possible, but you have to upload the whole image again to do it. This would be a shortcut POST with just the filereference and etag.

**Comment by UnwashedMeme** [comment]
This is tested and working
