### ISSUE TITLE
Python client not retrieving by fields

### ISSUE THREAD

**Issue by ialzuru** [iDigBio/idigbio-python-client#9]
Hello,

We are trying to access the iDigBio data using the python API. In some cases I would like to retrieve only a couple of fields. I have tried using the api.search_records() function with the "fields" clause in several ways but the function returns all the fields or no data at all.
Please, could you provide some example about how to get only several fields (in python)?
Using GET requests (REST API) this feature works.
Thank you,

Icaro Alzuru

**Comment by godfoder** [comment]
An example of doing this in the current in the current python client can be see in this notebook:

https://gist.github.com/godfoder/9dfc9b2a2b9023d0ae8051cf49a3d0af

**Comment by ialzuru** [comment]
I see that it works for fields in the "indexTerms" set, but it returns all the fields of the recordset.
Is there any way to restrict the fields of the recordsets or "data" set?

Thank you
